import type { Metadata } from "next";
import "../globals.css";
import Footer from "@/app/components/Footer";
import { CartProvider } from "@/app/cartContext";
import { ClerkProvider, SignedOut } from "@clerk/nextjs";
import Navbar from "@/app/components/Navbar";
import Topbar from "@/app/components/Topbar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
      <html lang="en">
        <CartProvider>
          <body>
            <SignedOut></SignedOut>
            <Topbar/>
            <Navbar/>
            {children}
            
            <Footer />
          </body>
        </CartProvider>
      </html>
    </ClerkProvider>
  );
}
