import { CartProvider } from "@/app/cartContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
       <CartProvider>
       <body>{children}</body>
       </CartProvider>
      
    </html>
  );
}
